'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { LoaderCircle } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
type Category = { id: string; name: string; slug: string; description: string };
const empty = { name: '', slug: '', description: '' };
export function CategoriesManager({ initial }: { initial: Category[] }) {
  const router = useRouter(); const [form, setForm] = useState(empty); const [editing, setEditing] = useState<string | null>(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [deleting, setDeleting] = useState<string | null>(null);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(''); const response = await fetch(editing ? `/api/admin/categories/${editing}` : '/api/admin/categories', { method: editing ? 'PUT' : 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(form) }); setSaving(false); if (!response.ok) { setError((await response.json()).error); return; } setForm(empty); setEditing(null); router.refresh(); };
  const remove = async (category: Category) => { if (!confirm('Delete this category?')) return; setDeleting(category.id); setError(''); const response = await fetch(`/api/admin/categories/${category.id}`, { method: 'DELETE' }); setDeleting(null); if (!response.ok) setError((await response.json()).error); else router.refresh(); };
  return <><form onSubmit={save} className="mt-6 grid gap-3 rounded-2xl border bg-card p-5 md:grid-cols-[1fr_1fr_2fr_auto]"><Input placeholder="Name" required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value, slug: editing ? form.slug : event.target.value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') })} /><Input placeholder="Slug" required value={form.slug} onChange={(event) => setForm({ ...form, slug: event.target.value })} /><Input placeholder="Description" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /><Button disabled={saving || Boolean(deleting)}>{saving && <LoaderCircle className="h-4 w-4 animate-spin" aria-hidden="true" />}{saving ? 'Saving…' : editing ? 'Update' : 'Add'}</Button>{error && <p role="alert" className="text-sm text-destructive md:col-span-4">{error}</p>}</form><div className="mt-6 divide-y rounded-2xl border bg-card">{initial.map((category) => <div key={category.id} className="flex flex-col gap-3 p-4 md:flex-row md:items-center"><div className="flex-1"><p className="font-medium">{category.name} <span className="text-sm text-muted-foreground">/{category.slug}</span></p><p className="text-sm text-muted-foreground">{category.description}</p></div><Button variant="outline" disabled={saving || Boolean(deleting)} onClick={() => { setEditing(category.id); setForm({ name: category.name, slug: category.slug, description: category.description }); }}>Edit</Button><Button variant="ghost" disabled={saving || Boolean(deleting)} onClick={() => remove(category)}>{deleting === category.id && <LoaderCircle className="h-4 w-4 animate-spin" aria-hidden="true" />}{deleting === category.id ? 'Deleting…' : 'Delete'}</Button></div>)}</div></>;
}
