'use client';
import dynamic from 'next/dynamic';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { Textarea } from '@/components/ui/Textarea';
const MDEditor = dynamic(() => import('@uiw/react-md-editor'), { ssr: false });
type Option = { id: string; name: string };
type Initial = { id?: string; title: string; slug: string; excerpt: string; seoTitle: string; metaDescription: string; canonicalUrl: string; noIndex: boolean; content: string; coverImageUrl: string; coverAlt: string; categoryId: string; authorId: string; tags: string[]; status: 'draft' | 'published' };

export function PostEditor({ initial, categories, authors }: { initial: Initial; categories: Option[]; authors: Option[] }) {
  const router = useRouter(); const [form, setForm] = useState(initial); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const set = (key: keyof Initial, value: unknown) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(''); const response = await fetch(initial.id ? `/api/admin/posts/${initial.id}` : '/api/admin/posts', { method: initial.id ? 'PUT' : 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(form) }); setSaving(false); if (!response.ok) { const body = await response.json().catch(() => ({})); setError(body.error || 'Could not save post'); return; } router.push('/admin/posts'); router.refresh(); };
  return <form onSubmit={submit} className="mt-6 space-y-5">
    <div className="grid gap-5 md:grid-cols-2"><Field label="Title"><Input required value={form.title} onChange={(e) => { set('title', e.target.value); if (!initial.id) set('slug', e.target.value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')); }} /></Field><Field label="Slug"><Input required value={form.slug} onChange={(e) => set('slug', e.target.value)} /></Field></div>
    <Field label="Excerpt"><Textarea required value={form.excerpt} onChange={(e) => set('excerpt', e.target.value)} /></Field>
    <div className="grid gap-5 md:grid-cols-3"><Field label="Category"><select className="h-10 w-full rounded-lg border bg-background px-3" value={form.categoryId} onChange={(e) => set('categoryId', e.target.value)}>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Author"><select className="h-10 w-full rounded-lg border bg-background px-3" value={form.authorId} onChange={(e) => set('authorId', e.target.value)}>{authors.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Status"><select className="h-10 w-full rounded-lg border bg-background px-3" value={form.status} onChange={(e) => set('status', e.target.value)}><option value="draft">Draft</option><option value="published">Published</option></select></Field></div>
    <Field label="Tags (comma separated)"><Input value={form.tags.join(', ')} onChange={(e) => set('tags', e.target.value.split(',').map((tag) => tag.trim()).filter(Boolean))} /></Field>
    <div className="grid gap-5 md:grid-cols-2"><Field label="Cover image URL"><Input value={form.coverImageUrl} onChange={(e) => set('coverImageUrl', e.target.value)} /><input className="mt-2 text-sm" type="file" accept="image/*" onChange={async (e) => { const file = e.target.files?.[0]; if (!file) return; const data = new FormData(); data.set('file', file); const response = await fetch('/api/admin/upload', { method: 'POST', body: data }); const body = await response.json(); if (response.ok) set('coverImageUrl', body.url); else setError(body.error); }} /></Field><Field label="Cover alt text"><Input value={form.coverAlt} onChange={(e) => set('coverAlt', e.target.value)} /></Field></div>
    <section className="rounded-2xl border bg-secondary/30 p-5"><h2 className="font-serif text-xl font-semibold">Search appearance</h2><p className="mt-1 text-sm text-muted-foreground">Optional. Blank fields use the article title, excerpt, and normal public URL.</p><div className="mt-4 grid gap-5 md:grid-cols-2"><Field label="SEO title"><Input maxLength={250} value={form.seoTitle} onChange={(e) => set('seoTitle', e.target.value)} /></Field><Field label="Meta description"><Textarea maxLength={320} value={form.metaDescription} onChange={(e) => set('metaDescription', e.target.value)} /></Field></div><Field label="Canonical override"><Input type="url" placeholder="Leave blank for the normal article URL" value={form.canonicalUrl} onChange={(e) => set('canonicalUrl', e.target.value)} /></Field><label className="mt-4 flex items-start gap-3 text-sm"><input type="checkbox" className="mt-1 h-4 w-4" checked={form.noIndex} onChange={(e) => set('noIndex', e.target.checked)} /><span><strong className="block">Hide this published article from search engines</strong><span className="text-muted-foreground">Use only for intentional exclusions. Drafts are never public.</span></span></label></section>
    <Field label="Content (Markdown)"><div data-color-mode="light"><MDEditor value={form.content} onChange={(value) => set('content', value || '')} height={520} /></div></Field>
    {error && <p role="alert" className="text-destructive">{error}</p>}<div className="flex gap-3"><Button size="lg" disabled={saving}>{saving ? 'Saving…' : 'Save post'}</Button><Button type="button" size="lg" variant="outline" onClick={() => router.push('/admin/posts')}>Cancel</Button></div>
  </form>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-2 block text-sm font-medium">{label}</span>{children}</label>; }
